@startuml
class EventController {
    + CreateEvent(eventDate:DateTime, eventName:string, eventLocation:ILocation, eventReleaseDate:DateTime) : void
    + GetAllEventInfo() : string
    + GetAvailableTickets(eventName:string) : Dictionary<int, List<ITicket>>?
    + GetEvent(eventName:string) : IEvent?
}
class "List`1"<T> {
}
IEventController <|-- EventController
EventController o-> "ListOfEvents<IEvent>" "List`1"
@enduml
